name: 디스코드 알림봇

on:
  schedule: # UTC+9 기준 3시 실행
    - cron:  "35 1 * * *"

jobs:
  message:
    runs-on: ubuntu-latest
    steps:
    - name: Discord Webhook Action
      uses: tsickert/discord-webhook@v5.3.0
      with:
        webhook-url: ${${{ secrets.DISCORD }}}
        content: "써티 주간보고 작성 필요"
